runtime: python38 # or another supported version

instance_class: F1 # this is the cheapest option

env_variables:
  MYSQL_USER: 'root'
  MYSQL_PASSWORD: 'sourcecodesql'
  MYSQL_DB: 'url_shorten'
  MYSQL_HOST: '127.0.0.1'

handlers:

- url: /script
  static_dir: static/script

- url: /styles
  static_dir: static/styles